[features]
seeds = false
[programs.localnet]
tokenapp = "AshDfQYDD4cT9TeZW7LfS5JXfHRHyGpyjZsJUqfuaAGh"

[programs.devnet]
tokenapp = "AshDfQYDD4cT9TeZW7LfS5JXfHRHyGpyjZsJUqfuaAGh"

[programs.mainnet]
tokenapp = "AshDfQYDD4cT9TeZW7LfS5JXfHRHyGpyjZsJUqfuaAGh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/gtyuki/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
